---
title: "Hugh B. Crews"
output: pdf_document
geometry: margin=1in
fontsize: 11pt
header-includes:
- \newcommand{\bcenter}{\begin{center}}
- \newcommand{\ecenter}{\end{center}}
---

\bcenter
# Contact Information
\begin{center}
537 Mohican Trail\\
Wilmington, NC 28409\\
Phone: (910) 617-6928\\
Email: \href{mailto:hugh.crews@gmail.com}{hugh.crews@gmail.com}
\end{center}
\ecenter

# Education
\begin{itemize}
\item \textbf{May 2011}: Master of Business Administration, University of North Carolina Wilmington  
\item \textbf{August 2008}: Ph.D., Statistics, North Carolina State University\\  
  Advisors: Dr. Leonard Stefanski and Dr. Dennis Boos  \\
  Dissertation: \href{https://repository.lib.ncsu.edu/items/a3527216-396d-45e5-a0c7-c928477953f4}{\textit{Fast FSR Methods for Second-Order Linear Regression Models}}
\item \textbf{May 2005}: Master of Statistics, North Carolina State University  
\item \textbf{May 2003}: B.S., Statistics, Minor in Economics, North Carolina State University  

\end{itemize}
# Experience

- **Data Scientist, Eligis Analytics, Inc., Wilmington, NC** (April 2015 - Present)  
  - Consult with organizations to define key questions and decisions to improve their business.
  - Develop solutions for data collection, cleaning, and preparation.
  - Create applications and code snippets for recurring reports with data summaries and insights.
  - Build statistical models for prediction and analysis of relationships.
  - Develop applications for utilizing data and insights tailored to business needs.
  - Mentor new data science team members, interns, and students.
  - Explore and build prototype applications using modern APIs for developing LLM-based solutions

- **PhD Statistician, New Hanover Regional Medical Center, Wilmington, NC** (July 2013 - March 2015)  
  - Analyzed key quality measures and patient satisfaction data.
  - Developed graphical tools for reporting data to stakeholders.

- **Biostatistician III, PharPoint Research, Inc., Wilmington, NC** (September 2011 - May 2013)  
  - Conducted statistical analysis for clinical research.
  - Developed statistical analysis plans and programs for datasets, tables, listings, and figures.

- **Adjunct Professor, Mt. Olive College, Wilmington, NC** (December 2008 - December 2012)  
  - Taught introductory statistics courses in business and healthcare management programs.

- **Visiting Research Assistant Professor, University of North Carolina Wilmington, Wilmington, NC** (December 2008 - September 2011)  
  - Consulted on experimental design and analysis for university researchers.

- **Development Tester II, SAS Institute, Cary, NC** (June 2008 - November 2008)  
  - Tested and documented bugs for various JMP platforms.

- **Student Co-op, Environmental Protection Agency, Durham, NC** (September 2006 - December 2006)  
  - Analyzed historical trends of principal air pollutants using regression and imputation techniques.

- **Teaching Assistant, North Carolina State University** (August 2005 - May 2006)  
  - Taught introductory statistics courses during fall and spring semesters.

- **Technical Student, SAS Institute, Cary, NC** (Various dates 2001 - 2006)  
  - Conducted testing, documentation, and programming tasks for SAS platforms.

# Research Interests

\begin{itemize}
\item Variable and model selection
\item Time series analysis
\item Data mining
\item Business analytics
\item LLM prompt engineering and applications
\end{itemize}

# Honors and Awards

\begin{itemize}
\item 2011: Elected Beta Gamma Sigma Business Honor Society  
\item 2008 - 2011: MARBIONC Postdoc Fellow  
\item 2003 - 2008: NSF VIGRE Fellow  
\item 2003: GlaxoSmithKline Scholar Award  
\item 2003: Graduated Summa Cum Laude  
\item 2003: Elected Phi Kappa Phi Honor Society  
\item 2003: Elected Mu Sigma Rho Statistics Honor Society  
\item 2000 - 2003: SAS Scholar  
\end{itemize}

# Publications

\begin{itemize}
\item Crews, H.B., Boos, D.D., and Stefanski, L.A. (2011). \href{https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3072220/pdf/nihms269032.pdf}{FSR Methods for Second-Order Regression Models}. \textit{Computational Statistics and Data Analysis}, 55, 2026-2037.
\end{itemize}

# Computing/Technology Skills

\begin{itemize}
\item R, Python, SAS, Tableau  
\item Git, Asana  
\item REST API, SQL, AWS  
\item Excel/VBA, Word, LaTeX
\end{itemize}
